import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import CartProvider from './components/Providers'
import ShoppingCartModal from './components/ShoppingCartModal'





export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <CartProvider>
          <ShoppingCartModal/>
          <Navbar/>
          {children}
        </CartProvider>
        </body>
    </html>
  )
}
